### ISSUE TITLE
Finish CART decision tree

### ISSUE THREAD

**Issue by bfla** [buccaneerai/bottlenose#25]
Most of it is done in [this repository](https://github.com/buccaneerai/rxtree).  Once it's ready, it can be used to build a [random forest](https://github.com/karpathy/forestjs), extremely randomized forests and some other extremely useful algorithms.

It would also be nice to learn about streaming implementations like [dsCART](https://www.sciencedirect.com/science/article/pii/S0020025514000206) since CART is not an online algorithm.

Checklist:
- [x] Migrate rxtree over to bottlenose monorepo
- [ ] It should conform to the same classifier API as the SGD classifier (#21)
- [ ] It needs to be tested on some real data
- [ ] The implementation is a bit overcomplicated.  Could probably be simplified a bit.
- [x] Should allow a `preSorted` option.  This would prevent the need to re-sort the same data.

**Comment by Jwaein** [comment]
Hello, Mr. Brian Flaherty. I am a first-year graduate student, and I have learned about dsCART algorithm recently. However, due to my limited ability, I could not write The dsCART algorithm flow through The pseudo code in The paper of The CART Decision Tree for Mining Data Streams. Do you have the dsCART code? If you have it, can you send it to me for project research? Thank you very much!
